package puzzler;

//在注释中出现了"反斜杠u，但是后面不是一个Unicode码，所以会报错
//应该使用HTML实体转义字符来代替Unicode转义字符

/**
 * Generated by the IBM IDL-to-Java compiler, version 1.0
 * from F:\TestRoot\apps\a1\、(我加的)units\include\PolicyHome.idl
 * Wednesday, June 17, 1998 6:44:40 o'clock AM GMT+00:00
 */
public class Test {
    public static void main(String[] args) {
        System.out.print("Hell");
        System.out.println("o world");
    }
}